# Goal: Master workflow_dispatch and data types.
# Task: Write a workflow that only runs manually. It should accept two inputs: a boolean named run_tests and a 
# choice named environment (with options: dev, staging, prod).
name: Workflow Dispatch example

on:
    workflow_dispatch:
        inputs:
            run_tests:
                type: boolean
                description: 'Run test suite?'
            environment:
                type: choice
                description: 'Select the deployment environment'
                options: [dev, staging, prod]

# Goal: Access runtime metadata.
# Task: Add a job with a step that prints the name of the user who triggered the workflow and the name of the branch.
# Hint: Use the github context.                
jobs:
    context_practice:
        runs-on: ubuntu-latest
        steps:
            - name: Print runtime metadata
              run: echo "Workflow triggered by ${{ github.actor}} on ref ${{ github.ref}}"

# Goal: Pass static data securely to subsequent steps without using outputs.
# Task: Create a step that sets an environment variable for a C++ compiler flag. In the very next step, print that variable.
            - name: Set compiler flag
              run: echo "CXX_FLAGS=-O3" >> $GITHUB_ENV
            - name: Print compiler flag
              run: echo "Compiler flag is $CXX_FLAGS"

# Goal: Generate dynamic data in one step and selectively pass it to another using step IDs. (The exam heavily tests the difference between this and GITHUB_ENV).
# Task: Assign an id to a step. Inside that step, write a script that outputs a Python version number. In the next step, use the steps context to read it.
            - name: Set Python version
              id: py_setup
              run: echo "version=3.10" >> $GITHUB_OUTPUT
            - name: Read output
              run: echo "Python version is ${{ steps.py_setup.outputs.version}}"

# Goal: Generate multiple job executions from a single definition.
# Task: Create a new job called matrix_build. Configure a strategy matrix to run across two operating systems (ubuntu-latest, macos-latest) and two runtimes (node, python). Have the run step print both.

    matrix_build:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                runtime: [node, python]
                exclude:
                    - os: macos-latest
                      runtime: python
        runs-on: ${{ matrix.os}}
        steps:
            - name: Print matrix values
              run: echo "Running on ${{ matrix.os }} with runtime ${{ matrix.runtime }}"